[build]
  # 建置命令
  command = "npm run build"
  # 發布目錄
  publish = "dist"
  # 環境變數
  [build.environment]
    NODE_VERSION = "22"

# Edge Functions 設定
[[edge_functions]]
  path = "/news/*"
  function = "news-meta"

# 重定向規則
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dc"
  to = "https://discord.gg/3TEHPZhYUK"
  status = 301
  force = true

[[redirects]]
  from = "/xiaoheihe"
  to = "https://chat.xiaoheihe.cn/if6vxm4o"
  status = 301
  force = true

# 標頭設定
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 快取設定
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 環境變數
[context.production.environment]
  VITE_APP_ENV = "production"
  # 請在 Netlify Dashboard 中設定以下環境變數：
  # VITE_SUPABASE_URL = "your_production_supabase_url"
  # VITE_SUPABASE_ANON_KEY = "your_production_supabase_anon_key"
  # VITE_DISCORD_WEBHOOK_URL = "your_discord_webhook_url"

[context.deploy-preview.environment]
  VITE_APP_ENV = "staging"
  # 請在 Netlify Dashboard 中設定以下環境變數：
  # VITE_SUPABASE_URL = "your_staging_supabase_url"
  # VITE_SUPABASE_ANON_KEY = "your_staging_supabase_anon_key"
  # VITE_DISCORD_WEBHOOK_URL = "your_discord_webhook_url"

[context.branch-deploy.environment]
  VITE_APP_ENV = "development"
  # 請在 Netlify Dashboard 中設定以下環境變數：
  # VITE_SUPABASE_URL = "your_development_supabase_url"
  # VITE_SUPABASE_ANON_KEY = "your_development_supabase_anon_key"
  # VITE_DISCORD_WEBHOOK_URL = "your_discord_webhook_url" 